#version 460 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0) uniform sampler2D infield;
layout (binding = 1, rgba32f) writeonly uniform image2D outfield;
layout (binding = 2, rgba32f) writeonly uniform image2D outpos;

uniform SimulationConstants {
    float dt;
    float viscosity;
    float initialDensity;
    float densityFactor;
    vec2  gravity;
    vec2  delta;
    vec2  inv_delta;
    ivec2 dimensions;
} u_const;


bool clampBounds(inout ivec2 coords) {
    ivec2 tmp = clamp(ivec2(0, 0), u_const.dimensions - ivec2(1, 1), coords);
    bool value = (tmp == coords); /* equality means that no clamp was required - it's in range */
    
    coords = tmp;
    return value; /* True => In Range | False => Invalid Index */
}


void splitToNeighbours(in vec2 coordxy, out vec4 weights)
{
    /* 
        Illustration: 
        https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Bilinear_interpolation_visualisation.svg/170px-Bilinear_interpolation_visualisation.svg.png
    */
    vec2 ds = vec2(1, 1);
    vec2 x1y1 = floor(coordxy);
    vec2 x2y2 = x1y1 + ds;
    vec2 dxdy_bl = coordxy - x1y1;
    vec2 dxdy_tr = (ds - dxdy_bl);

    weights = vec4(
        dxdy_tr.x * dxdy_tr.y, /* Bottom Left  Weight <=> (i  , j  ) */
        dxdy_tr.x * dxdy_bl.y, /* Top    Left  Weight <=> (i  , j+1) */
        dxdy_bl.x * dxdy_tr.y, /* Bottom Right Weight <=> (i+1, j  ) */
        dxdy_bl.x * dxdy_bl.y  /* Top    Right Weight <=> (i+1, j+1) */
    );
    weights *= 1 / (ds.x * ds.y);
    return;
}


void main()
{
    const vec2 k_invDeltaSquared = u_const.inv_delta * u_const.inv_delta;
    const vec2 k_invDoubleDelta  = 0.5f * u_const.inv_delta;
    const float norm_viscosityFactor = u_const.viscosity / u_const.initialDensity;
    const float norm_densityFactor   = -1 * u_const.densityFactor * k_invDeltaSquared.x / (u_const.dt * u_const.initialDensity);
    const ivec2 offset[2] = {
        ivec2(1, 0),
        ivec2(0, 1)
    };
    const vec2 offsetf[2] = {
        1.0 / vec2(u_const.dimensions) * offset[0],
        1.0 / vec2(u_const.dimensions) * offset[1]
    };
    vec2  texelCoord  = vec2(gl_GlobalInvocationID.xy) / vec2(u_const.dimensions);
    ivec2 texelCoordi = ivec2(gl_GlobalInvocationID.xy);
    ivec2 sampleIndices[4] = {
        texelCoordi + offset[0], /* (i + 1, j    ) */
        texelCoordi - offset[0], /* (i - 1, j    ) */
        texelCoordi + offset[1], /* (i    , j + 1) */
        texelCoordi - offset[1]  /* (i    , j - 1) */
    };
    const bvec4 validSampleIndex = {
        clampBounds(sampleIndices[0]),
        clampBounds(sampleIndices[1]),
        clampBounds(sampleIndices[2]),
        clampBounds(sampleIndices[3])
    };
    vec4 samples[5] = {
        texelFetch(infield, texelCoordi, 0),
        vec4(float(validSampleIndex.x)) * texelFetch(infield, sampleIndices[0], 0),
        vec4(float(validSampleIndex.y)) * texelFetch(infield, sampleIndices[1], 0),
        vec4(float(validSampleIndex.z)) * texelFetch(infield, sampleIndices[2], 0),
        vec4(float(validSampleIndex.w)) * texelFetch(infield, sampleIndices[3], 0)
    };
    vec4 grad_ij[3];
    float div_ij[2];
    vec2 laplacian_ij;
    vec2 tmp0, tmp1;
    grad_ij[0] = vec4(k_invDoubleDelta, k_invDoubleDelta.x, 0) * (samples[1] - samples[2]);
    grad_ij[1] = vec4(k_invDoubleDelta, k_invDoubleDelta.y, 0) * (samples[3] - samples[4]);
    grad_ij[2] = vec4(grad_ij[0].z, grad_ij[1].z, 0, 0); /* pressure gradient */
    div_ij[0] = grad_ij[0].x + grad_ij[1].y; /* velocity divergence */
    div_ij[1] = grad_ij[0].z + grad_ij[1].z; /* pressure divergence */
    
    tmp0 = k_invDeltaSquared.x * (samples[1].xy + samples[2].xy - samples[0].xy);
    tmp1 = k_invDeltaSquared.y * (samples[3].xy + samples[4].xy - samples[0].xy);
    laplacian_ij = tmp0 + tmp1;


    float new_density = samples[0].z - u_const.dt * ( dot( samples[0].xy, grad_ij[2].xy ) + samples[0].z * div_ij[0] );
    vec2 new_velocity = vec2(0.0f);

    tmp0 = ( vec2(texelCoordi) - u_const.dt * samples[0].xy ) / u_const.dimensions;
    new_velocity += texture(infield, tmp0).xy;
    new_velocity += samples[0].xy + u_const.dt * ( norm_densityFactor * grad_ij[2].xy + u_const.gravity + norm_viscosityFactor * laplacian_ij );


    /* Boundary Conditions */
    new_velocity *= vec2(bvec2(
        any(validSampleIndex.xy),
        any(validSampleIndex.zw)
    ));
    // imageStore(outfield, texelCoordi, vec4(new_velocity, new_density, 0.0f));


    tmp0 = vec2(texelCoordi) + u_const.dt * new_velocity;
    tmp1 = floor(tmp0);
    vec4 neighbour_weights;
    splitToNeighbours(tmp0, neighbour_weights);
    vec2 neighbour_values[4] = vec2[4](
        new_velocity * neighbour_weights.x,
        new_velocity * neighbour_weights.y,
        new_velocity * neighbour_weights.z,
        new_velocity * neighbour_weights.w
    );

    // imageStore(outpos, ivec2(tmp0) + ivec2(0, 0), vec4( neighbour_values[0], 0.0f, 1.0f) );
    // imageStore(outpos, ivec2(tmp0) + ivec2(0, 1), vec4( neighbour_values[1], 0.0f, 1.0f) );
    // imageStore(outpos, ivec2(tmp0) + ivec2(1, 0), vec4( neighbour_values[2], 0.0f, 1.0f) );
    // imageStore(outpos, ivec2(tmp0) + ivec2(1, 1), vec4( neighbour_values[3], 0.0f, 1.0f) );

    
    // imageStore(outpos, ( ivec2(tmp0) + ivec2(0, 0) ), vec4(vec3(validSampleIndex.x), 1.0f) );
    // imageStore(outpos, ( ivec2(tmp0) + ivec2(0, 1) ), vec4(vec3(validSampleIndex.y), 1.0f) );
    // imageStore(outpos, ( ivec2(tmp0) + ivec2(1, 0) ), vec4(vec3(validSampleIndex.z), 1.0f) );
    // imageStore(outpos, ( ivec2(tmp0) + ivec2(1, 1) ), vec4(vec3(validSampleIndex.w), 1.0f) );
    // imageStore(outpos, ivec2(tmp0), vec4(1.0f));
    imageStore(outfield, texelCoordi, samples[0]);
    imageStore(outpos, texelCoordi, samples[0]);
    // imageStore(outpos, texelCoordi, vec4(new_velocity.xy, 0.0f, 1.0f));
}


// imageStore(outpos, ivec2(tmp0), vec4(validSampleIndex.zw, 0.0f, 0.0f) ); /* Check Bounds Checking */
// imageStore(outpos, ivec2(tmp0), vec4(validSampleIndex.xy, 0.0f, 0.0f) ); /* Check Bounds Checking */
// if( !validSampleIndex.x || !validSampleIndex.y )
//     new_velocity.x *= !( !validSampleIndex.x || !validSampleIndex.y );
// if( !validSampleIndex.z || !validSampleIndex.w )
//     new_velocity.y = 0.0f;