#version 460 core
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout (binding = 0, rgba32f) readonly uniform image2D infield;
layout (binding = 1, rgba32f) writeonly uniform image2D outfield;
layout (binding = 2, rgba32f) writeonly uniform image2D outpos;

uniform SimulationConstants {
    float dt;
    float viscosity;
    float initialDensity;
    float densityFactor;
    vec2  gravity;
    vec2  delta;
    vec2  inv_delta;
    ivec2 dimensions;
} u_const;


bool clampBounds(inout ivec2 coords) {
    const ivec2 minSimBounds = (0, 0);
    const ivec2 maxSimBounds = u_const.dimensions - uvec2(1);
    ivec2 tmp = clamp(minSimBounds, maxSimBounds, coords);
    bool value = (tmp == coords); 
    
    coords = tmp;
    return value;
}


void main()
{
    const vec2 k_invDeltaSquared = u_const.inv_delta * u_const.inv_delta;
    const vec2 k_invDoubleDelta  = 0.5f * u_const.inv_delta;
    const float norm_viscosityFactor = u_const.viscosity / u_const.initialDensity;
    const float norm_densityFactor   = -1 * u_const.densityFactor * k_invDeltaSquared.x / (u_const.dt * u_const.initialDensity);
    const ivec2 offset[2] = {
        vec2(1, 0),
        vec2(0, 1)
    };
    uvec2 texelCoord = gl_GlobalInvocationID.xy;
    const ivec2 sampleIndices[4] = {
        texelCoord + offset[0], /* (i + 1, j    ) */
        texelCoord - offset[0], /* (i - 1, j    ) */
        texelCoord + offset[1], /* (i    , j + 1) */
        texelCoord - offset[1]  /* (i    , j - 1) */
    };
    const bvec4 invalidSampleIndex = {
        clampBounds(sampleIndices[0]),
        clampBounds(sampleIndices[1]),
        clampBounds(sampleIndices[2]),
        clampBounds(sampleIndices[3])
    };
    vec4 samples[5] = {
        imageLoad(infield, texelCoord),
        vec4(float(invalidSampleIndex.x)) * imageLoad(infield, sampleIndices[0]),
        vec4(float(invalidSampleIndex.y)) * imageLoad(infield, sampleIndices[1]),
        vec4(float(invalidSampleIndex.z)) * imageLoad(infield, sampleIndices[2]),
        vec4(float(invalidSampleIndex.w)) * imageLoad(infield, sampleIndices[3])
    };
    vec4 grad_ij[3];
    float div_ij[2];
    vec2 laplacian_ij;
    vec2 __tmp0, __tmp1;
    grad_ij[0] = vec4(k_invDoubleDelta, k_invDoubleDelta.x, 0) * (samples[1] - samples[2]);
    grad_ij[1] = vec4(k_invDoubleDelta, k_invDoubleDelta.y, 0) * (samples[3] - samples[4]);
    grad_ij[2] = vec4(grad_ij[0].z, grad_ij[1].z, 0, 0); /* pressure gradient */
    div_ij[0] = grad_ij[0].x + grad_ij[1].y; /* velocity divergence */
    div_ij[1] = grad_ij[0].z + grad_ij[1].z; /* pressure divergence */
    
    __tmp0 = k_invDeltaSquared.x * (samples[1].xy + samples[2].xy - samples[0].xy);
    __tmp1 = k_invDeltaSquared.y * (samples[3].xy + samples[4].xy - samples[0].xy);
    laplacian_ij = __tmp0 + __tmp1;


    float new_density = samples[0].z - u_const.dt * ( dot( samples[0].xy, grad_ij[2].xy ) + samples[0].z * div_ij[0] );
    vec2 new_velocity = 0.0f;
    new_velocity += imageLoad( infield, vec2(texelCoord) - u_const.dt * samples[0].xy );
    new_velocity += samples[0].xy + u_const.dt * ( norm_densityFactor * grad_ij[2].xy + u_const.gravity + norm_viscosityFactor * laplacian_ij );


    /* Boundary Conditions */
    new_velocity *= vec2(bvec2(
        !any(invalidSampleIndex.xy),
        !any(invalidSampleIndex.zw)
    ));

    /* Stability Conditions */
}