COMPILER_BASE_FOLDER = "$(shell printenv COMPILER_BASE_FOLDER)"
PROJECT_FOLDER_BASE  = $(shell pwd)
PROJECT_FOLDER       = "$(shell cygpath -m $(PROJECT_FOLDER_BASE))"


BUILDDIR_BASE 	   :=build
APPEND_RELEASE_DIR :=release
APPEND_DEBUG_DIR   :=debug
APPEND_DIR_CHOSEN  :=
BUILDDIR 		   :=$(BUILDDIR_BASE)/

ifndef DEBUG
$(error DEBUG variable isn't defined. Can't proceed with build process)
else
$(info [DEBUG='$(DEBUG)'] DEBUG    Variable defined		   )
$(info [DEBUG='$(DEBUG)'] BUILDDIR Variable ["$(BUILDDIR)"])
endif

ifeq ('$(DEBUG)' , '1')
	APPEND_DIR_CHOSEN:=$(APPEND_DEBUG_DIR)
else
	APPEND_DIR_CHOSEN:=$(APPEND_RELEASE_DIR)
endif


SRCDIR    := src
BUILDDIR  := $(BUILDDIR)$(APPEND_DIR_CHOSEN)
OBJDIR    := $(BUILDDIR)/obj
OUTPUTDIR := $(BUILDDIR)/bin
$(info [DEBUG='$(DEBUG)'] BUILDDIR Variable ["$(BUILDDIR)"] )




PROJNAME = awc
TARGET   = $(PROJNAME).exe
LINKER   = $(COMPILER_BASE_FOLDER)/bin/lld-link.exe
CPPC  	 = $(COMPILER_BASE_FOLDER)/bin/clang++.exe
CC  	 = $(COMPILER_BASE_FOLDER)/bin/clang.exe
ASMC 	 = $(COMPILER_BASE_FOLDER)/bin/clang.exe
ASMFLAGS = -O0
CVERSION   = c11
CXXVERSION = c++17

CXXFLAGS_RELEASE = \
	-O3 \
	-ffast-math \

CXXFLAGS_DEBUG = \
	-g \
	-Os \
	-D_DEBUG \
	--verbose \

CXXFLAGS = \
	-c \
	-pedantic \
	-Werror \
	-Wall \
	-Wextra \
	-march=native \
	-mtune=native \

# --verbose \

ifeq ('$(DEBUG)' , '1')
	CXXFLAGS += $(CXXFLAGS_DEBUG)
else
	CXXFLAGS += $(CXXFLAGS_RELEASE)
endif


LIB_FILES     = \
	-lglbinding \
	-lglbinding-aux \
	-lglfw3 \
	-ldevkit_$(APPEND_DIR_CHOSEN) \

LIB_INC_PATHS = \
	-I$(COMPILER_BASE_FOLDER)/ext/GLFW/include \
	-I$(COMPILER_BASE_FOLDER)/ext/staticdevkit/include \
	-I$(COMPILER_BASE_FOLDER)/ext/glbinding/include \
	-I$(PROJECT_FOLDER)/src \

LIB_PATHS     = \
	-L$(COMPILER_BASE_FOLDER)/ext/GLFW/lib \
	-L$(COMPILER_BASE_FOLDER)/ext/staticdevkit/lib \
	-L$(COMPILER_BASE_FOLDER)/ext/glbinding/lib \
	-L$(COMPILER_BASE_FOLDER)/

LDFLAGS = \
		-fuse-ld=lld \
		-flto \
		-lgdi32 \
		-lpthread \
		-static-libstdc++ \
		$(LIB_FILES) \
		-ferror-limit=0 \

# -lpthread \
# -flto \
# -lunwind \
# -lopengl32 \
# -lm \
# -dl \




rwildcard=$(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))

CSRC    = $(call rwildcard,$(SRCDIR),*.c)
CPPSRC += $(call rwildcard,$(SRCDIR),*.cpp)
ASMSRC  = $(call rwildcard,$(SRCDIR),*.asm)
OBJS  = $(patsubst $(SRCDIR)/%.asm,$(OBJDIR)/%_asm.o,$(ASMSRC))
OBJS += $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%_c.o,$(CSRC))
OBJS += $(patsubst $(SRCDIR)/%.cpp,$(OBJDIR)/%_cpp.o,$(CPPSRC))


# Compile All C, C++, ASM Files that are part of the source directory
$(OBJDIR)/%_asm.o: $(SRCDIR)/%.asm
	@ echo -n "[COMPILE][ASM]["$^"] "
	@ mkdir -p $(@D)
	$(ASMC) $(ASMFLAGS) $^ -o $@


$(OBJDIR)/%_c.o: $(SRCDIR)/%.c
	@ echo -n "[COMPILE][C]["$^"] "
	@ mkdir -p $(@D)
	$(CC) -std=$(CVERSION) $(CXXFLAGS) $(LIB_INC_PATHS) $^ -o $@ 


$(OBJDIR)/%_cpp.o: $(SRCDIR)/%.cpp
	@ echo -n "[COMPILE][CXX]["$^"] "
	@ mkdir -p $(@D)
	$(CPPC) -std=$(CXXVERSION) $(CXXFLAGS) $(LIB_INC_PATHS) $^ -o $@




link:
	@ echo Linking ...
	$(CPPC) $(LIB_PATHS) $(OBJS) -o $(OUTPUTDIR)/$(TARGET) $(LDFLAGS)


build: $(OBJS) link



# Don't Forget to Pipe the Output to a text file! (==> make debug_compile &> debug_out.txt)
debug_compile: CXXFLAGS += --verbose
debug_compile: build


clean_internal:
	@ echo -n "Deleting Compiled Files ... "  
	-@ rm -r $(OBJDIR)/* &> /dev/null || true
	@ echo "Done! "


cleanbin_internal:
	@ echo -n "Deleting Project Executable ... "
	-@ rm -r $(OUTPUTDIR)/$(TARGET) &> /dev/null || true
	@ echo "Done! "


run:
	@ echo " Running Compiled Executable ... "
	./$(OUTPUTDIR)/$(TARGET)

info:
	@ echo -e "File List: $(ASMSRC) $(CSRC) $(CPPSRC)\nObject List: $(OBJS)\n"



.PHONY: info run cleanall cleanbin